name: bench

on:
  workflow_dispatch:

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-2025
            label: windows-2025
            arch: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo bench --bench instant -- --warm-up-time 1 --measurement-time 3
      - name: Upload criterion output
        uses: actions/upload-artifact@v4
        with:
          name: criterion-${{ matrix.label }}
          path: target/criterion/
